theme: jekyll-theme-minimal

title: "Uladzimir Akulovich"
logo: uladakulovich.png

description: "Android Developer"

# Github
github.is_project_page: false

# Google services
google_analytics: UA-157612102-1